In [6]:
from numpy import linalg
import numpy as np

In [7]:
## ЗАДАЧА 1 ##

value = int(input('Введите значение '))
np.arange(value - 1, -1, -1)

Введите значение 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [8]:
## ЗАДАЧА 2 ##

value = int(input('Введите значение '))
matrix = np.diag(np.flip(np.arange(0, value), 0),0)
print(matrix)
print(f'Сумма элементов на диагонали {np.trace(matrix)}')

Введите значение 10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма элементов на диагонали 45


In [9]:
## ЗАДАЧА 3 ##

r_part = np.array( [4, 12, -3] )
l_part = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
linalg.solve(l_part, r_part)

array([ 0.46666667,  3.84444444, -5.55555556])

In [29]:
## ЗАДАЧА 4 ##

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

result = {}
for i, customer in  enumerate(users_stats):
    value = cosine(next_user_stats, customer)
    result[i + 1] = value

print(f'Номер наиболее близкого покупателя: {[num for num, value in result.items() if value == max(result.values())][0]}')

Номер наиболее близкого покупателя: 8
